### ISSUE TITLE
Integrate opam-repository webhooks

### ISSUE THREAD

**Issue by tmcgilchrist** [benmandrew/compiler-ci#28]
Currently there is a registered web hook on opam-repository for [ocaml-multicoretests.ci.dev:8100](https://ocaml-multicoretests.ci.dev:8100/). Further configuration is required in the deployment to setup reading this web hook and updating the pipeline based off new package versions.

**Comment by jmid** [comment]
I'm still not sure I understand the suggested setup fully. Allow me to elaborate...

AFAIU, there are two orthogonal issues:
- testing of compiler `trunk` packages, such as `ocaml-variants.5.2.0+trunk` which ATM follows the `trunk` development branch on the compiler repo
- running ci with the latest required packages (`qcheck-core`, `dune`, ...)


I can see that a webhook on `opam-repository` helps with the second of these, as a merge to it may trigger a 'cache entry dismissal'.

It is trickier with the first one as development on the compiler repo happens independently of the opam-repo.
AFAICS, the following situations can arise:
- changes on both repos trigger a cache flush (yay!)
- changes on neither repos retains a cache entry (fine)
- changes on opam-repo, but no compiler changes triggers a cache flush (needless, but harmless)
- changes on compiler repo, but no compiler changes retains a cache entry (we temporarily test a previous version)

As merges happen more often on the opam-repo that on the compiler, I suspect that the latter situation is more rare, and so the `opam-repo` webhook may be good enough:tm:.

**Comment by benmandrew** [comment]
The webhook seems to be working correctly, with the latest commits of `opam-repository` being used.

@jmid your points are correct and we'd probably require ANOTHER webhook, this time into `ocaml/ocaml`, to detect this. I've opened an issue (https://github.com/ocurrent/multicoretests-ci/issues/31) for this, and will close this one.
